### ISSUE TITLE
Thank you very much for this great app. Could you add option to run it on cpu or igpu, please?

### ISSUE THREAD

**Issue by JohnClaw** [ZDisket/WinDiffusion#1]
Hi. I tried to generate images using your app but it closed during the process. Before starting image generation i ran inner WinDiffussion benchmark that my igpu didn't passed because my igpu is AMD Radeon Graphics Vega 7 integrated in cpu Ryzen 7 4700u. But i know that even my weak igpu can generate images. I used app coded in C# - Amuse: https://huggingface.co/Stackyard-AI/Amuse/resolve/main/Amuse_v1.4.0_alpha.zip?download=true Amuse allows to use igpu to generate images with help of DirectML and onnx technologies. As far as i know C++ compiler is more well-optimized for fast performance than C# and produces more native executables. So, could you add igpu and cpu support, please?

**Comment by ZDisket** [comment]
The Check GPU dialog is more, well, for guidance, you don't have to treat it like the gospel. ~~Have you tried generating images?~~ (nevermind, you did). Theoretically as long as you have enough system RAM an iGPU should work. 
Right now, development is more focused on getting basic features and experience refined, but wider device support is something on the list - _if I can ever get this app noticed in the first place_.

**Comment by JohnClaw** [comment]
Thanks for the answer. I think that generation failure could be caused by realtime mode when every sampling step is immediately displayed. This mode is not compatible with igpu. How can i turn off realtime generation?

**Comment by ZDisket** [comment]
The sampling preview uses a separate, tiny model to display the denoising process, and said model is loaded and used in the same way as all the others, so I don't think it's the issue. Does the program fail at the end of the generation process? (like, when it's 100%)

**Comment by JohnClaw** [comment]
From my expierience, that i got by using other apps, realtime live preview requires powerful hardware. My igpu usually fails to generate image and display it's preview at the same time. That's why ask for adding an option to turn it off.  The program fails at 30%.

**Comment by JohnClaw** [comment]
Does WinDiffusion create any error.log somewhere in system folder? I wish i could upload it here to make things more clear.

**Comment by ZDisket** [comment]
No logging yet or much in the way of error handling, been neglecting that part. I still don't believe that realtime preview is the problem, but I can add something to turn it off

**Comment by JohnClaw** [comment]
> No logging yet or much in the way of error handling, been neglecting that part. I still don't believe that realtime preview is the problem, but I can add something to turn it off

Do it, please.
