### ISSUE TITLE
Native Windows GUI app to chat with such onnx models like Microsoft  Phi-3-mini?

### ISSUE THREAD

**Issue by JohnClaw** [ZDisket/WinDiffusion#2]
Could you create it, please?

**Comment by ZDisket** [comment]
I though there were like 5 trillion native local LLM apps out.

**Comment by JohnClaw** [comment]
> I though there were like 5 trillion native local LLM apps out.

There are no native gui apps for onnx llms. If you know at least one, share link, please. I can't find such app.

**Comment by ZDisket** [comment]
But there are plenty of llama.cpp ones. Well, I was already thinking of adding a tiny LLM to auto-refine prompts, but I really don't want to develop software if there's nobody to use it. Can you promote it on places like Reddit?
